### ISSUE TITLE
about SSPLv1

### ISSUE THREAD

**Issue by qiankunli** [FalkorDB/FalkorDB#817]
We have a tob RAG knowledge base product and want to incorporate a knowledge graph to improve the answer'quality of some questions. Considering that FalkorDB uses the SSPLv1 open source license, do we also need to open source our RAG product's code?

**Comment by gkorland** [comment]
hi @qiankunli what do you mean by "a tob RAG knowledge base product"?
Technically if your product doesn't offer FalkoprDB functionality as a service to your user you can use it without the need to open source your product.

**Comment by qiankunli** [comment]
> hi @qiankunli what do you mean by "a tob RAG knowledge base product"? Technically if your product doesn't offer FalkoprDB functionality as a service to your user you can use it without the need to open source your product.

We are providing a service similar to a customer support or knowledge assistant for enterprises. Customers upload various documents, such as research papers, employee manuals, and technical documents, to our product. Then, they can open a chat window and ask questions to receive answers. We want to use a knowledge graph to improve the quality of answers, especially for cross-chunk questions.

**Comment by gkorland** [comment]
From what you described you can use the FalkorDB without the impact of SSPL on your source

**Comment by MrHamel** [comment]
> Considering that FalkorDB uses the SSPLv1 open source license

The moment restrictions are placed on who can use the software, it is not truly open. Please read the OSI's definition of [open source.](https://opensource.org/osd) [The Open Source Initiative has deemed this to not be an open source license.](https://opensource.org/blog/the-sspl-is-not-an-open-source-license) [MongoDB themselves has also withdrew the license due to pushback.](https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2019-March/003989.html)

I do not care about the usage of the license, but the fact is the company claims it is open, which says something about their ethics/morals.

---

This project was brought to my attention by your sales staff reaching out via LinkedIn, and this spoke out to me.
